---
- name: Configure Windows Server
  hosts: all
  tasks:
    #############################################################################
    # Install Azure CLI
    #############################################################################
    - name: Install Azure CLI
      win_shell: |
        Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile AzureCLI.msi
        Start-Process msiexec.exe -ArgumentList '/I AzureCLI.msi /quiet' -Wait
        Remove-Item -Path AzureCLI.msi

    #############################################################################
    # Create a directory
    #############################################################################
    - name: Create directory C:\sls-module-admin
      win_file:
        path: C:\sls-module-admin
        state: directory

    #############################################################################
    # Install network utilities
    #############################################################################
    - name: Install network utilities
      win_shell: |
        Install-WindowsFeature -Name RSAT-Tools
        Install-WindowsFeature -Name Telnet-Client